# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_ordermodel_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='ticket',
        ),
        migrations.AddField(
            model_name='usermdel',
            name='ticket',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
